# Generated by Django 5.0 on 2024-01-13 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resqroute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='resqroute.node'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='resqroute.node'),
        ),
    ]
