# Generated by Django 5.0 on 2024-02-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resqroute', '0005_alter_map_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='img',
            field=models.ImageField(null=True, upload_to='maps'),
        ),
    ]
