# Generated by Django 5.0 on 2024-02-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resqroute', '0006_alter_map_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brigada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('functions', models.TextField(blank=True)),
            ],
        ),
    ]
