# Generated by Django 5.0 on 2024-02-13 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resqroute', '0007_brigada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brigada',
        ),
    ]
