# Generated by Django 5.0 on 2024-02-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resqroute', '0008_delete_brigada'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='faculty',
            field=models.IntegerField(choices=[(0, 'Salud'), (1, 'Energía'), (2, 'Jurídica'), (3, 'Educativa'), (4, 'Agropecuaria')], null=True),
        ),
    ]
